import sqlite3
from datetime import datetime

DB_PATH = "/data/data/com.termux/files/home/codac-coin_portal/database/codac_master.db"
REPORT_FILE = "/data/data/com.termux/files/home/codac-coin_portal/ledger_audit_jan29.txt"

def generate_report():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    with open(REPORT_FILE, "w") as f:
        f.write("=========================================================================\n")
        f.write(f"          📜 CODAC MASTER LEDGER AUDIT REPORT - {timestamp}\n")
        f.write("=========================================================================\n\n")
        
        f.write(f"{'PORTAL ID':<30} | {'NAME/LABEL':<25} | {'BALANCE':<15} | {'LOCKED':<8}\n")
        f.write("-" * 85 + "\n")

        cur.execute("SELECT user_id, name, trading_points, locked_balance FROM active_members ORDER BY is_system_account DESC, user_id ASC")
        rows = cur.fetchall()
        
        for row in rows:
            uid, name, balance, locked = row
            f.write(f"{uid:<30} | {name[:25]:<25} | {balance:<15,.4f} | {locked:<8.2f}\n")

        # System Totals
        cur.execute("SELECT SUM(trading_points), SUM(locked_balance) FROM active_members")
        total_circ, total_lock = cur.fetchone()
        
        f.write("\n=========================================================================\n")
        f.write(f" 🌐 TOTAL CIRCULATION: {total_circ or 0:,.4f} CODAC\n")
        f.write(f" 🔒 TOTAL SYSTEM LOCK: {total_lock or 0:,.2f} CODAC\n")
        f.write("=========================================================================\n")
        f.write(" REPORT GENERATED BY FOUNDER AUTHORITY PORTAL\n")

    print(f"\n✅ SUCCESS: Audit Report saved to: {REPORT_FILE}")
    conn.close()

if __name__ == "__main__":
    generate_report()
